version: '3.9'
services:
  develop:
    image: 'node:16.8-alpine3.11'
    container_name: digital-menu-app
    restart: always
    working_dir: /home/digitalmenu/app
    ports:
      - 8080:8080
    volumes:
      - .:/home/digitalmenu/app
      - ./node_modules:/home/digitalmenu/app/node_modules
    command: "sh -c 'npm install && npm run serve'"
